export const ADD_DATA = "ADD_DATA";
export const CLEAR_DATA = "CLEAR_DATA";
export const ADD_CERTIFICATE = "ADD_CERTIFICATE";
export const REMOVE_STATE = "REMOVE_STATE";
export const REMOVE_CERTIFICATE = "REMOVE_CERTIFICATE";